// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Src.Connection;

#nullable disable

namespace notaFiscal_api.Migrations
{
    [DbContext(typeof(NotaDbContext))]
    [Migration("20231220005650_01_AdicionarRelacaoClienteNotaFiscal")]
    partial class _01_AdicionarRelacaoClienteNotaFiscal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Src.Api.Domain.Models.ClienteModels.ClienteModel", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Cpf");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Src.Api.Domain.Models.NotaFiscalModels.NotaFiscalModel", b =>
                {
                    b.Property<string>("IdNota")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ValorTotal")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("IdNota");

                    b.HasIndex("Cpf");

                    b.ToTable("notaFiscal");
                });

            modelBuilder.Entity("Src.Api.Domain.Models.NotaFiscalModels.NotaFiscalModel", b =>
                {
                    b.HasOne("Src.Api.Domain.Models.ClienteModels.ClienteModel", "Cliente")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("Cpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Src.Api.Domain.Models.ClienteModels.ClienteModel", b =>
                {
                    b.Navigation("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
